name: deployment

on:
  push:
    branches: [ "main" ]


  workflow_dispatch:

env:
  BUCKET: paraskambojbuc
  TFSTATE_FILE: S3.tfstate
  aws_region: us-east-1

jobs:

  terraform_actions:

    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: set up terraform hasicrop
        uses: hashicorp/setup-terraform@v1

        with:
          terraform_version: 1.1.7


      - name: configure aws cridentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: $aws_region




      - name: Run a multi-line script
        run: |
            cd example
            terraform init -reconfigure -backend-config="bucket=$BUCKET" -backend-config="key=$TFSTATE_FILE"
